app/auth.py
from flask import Blueprint, render_template, flash, url_for, redirect, session
from flask_login import login_user, logout_user, current_user, login_required
from .wtform_fields import RegistrationForm, LoginForm
from werkzeug.security import check_password_hash
from .models import *
from app import app
from .socket import client_sid

auth = Blueprint("auth", __name__)

@auth.route("/sign-up", methods=["GET", "POST"])
def sign_up():
    if not current_user.is_authenticated:
        reg_form = RegistrationForm()

        if reg_form.validate_on_submit():
            username = reg_form.username.data
            email = reg_form.email.data
            password = reg_form.password.data

            hashed_pswd = generate_password_hash(password, method="sha256")

            user = User(username=username, email=email, password=hashed_pswd)

            db.session.add(user)
            db.session.commit()

            flash("Registration was successful", category="success")
            return redirect(url_for("auth.login"))

        else:
            for error in reg_form.errors.values():
                flash(error[0], category="error")

        return render_template("sign-up.html", form=reg_form, user=current_user)

    else:
        logout_user()
        return redirect(url_for("views.index"))

@auth.route("/login", methods=["GET", "POST"])
def login():

    login_form = LoginForm()

    if login_form.validate_on_submit():
        username = login_form.username.data
        password = login_form.password.data

        user = User.query.filter_by(username=username).first()

        if user:
            if check_password_hash(user.password, password):
                if not user.username in client_sid:
                    login_user(user)
                    flash("Logged in successfully", category="success")
                    session["current_room"] = "Lobby"
                    return redirect(url_for("views.chat"))
                else:
                    flash("Already logged in. You can only use one device at a time", category="error")
            else:
                flash("Password is incorrect", category="error")
        else:
            flash(f"No user named {username}", category="error")

    return render_template("login.html", form=login_form, user=current_user)

@auth.route("/logout", methods=["GET", "POST"])
@login_required
def logout():
    logout_user()
    flash("Logged out successfully", category="success")
    return redirect(url_for("views.index"))

@app.login_manager.unauthorized_handler
def unauth_handler():
    return redirect(url_for("views.index"))

app/templates/about.html
{% extends "base.html" %} {% block title %} Chat {% endblock %}
{% block content %}
    <h1>About</h1><br>
        <div class="about" style="margin: auto; text-align: center;">
            <h2 style="padding: 20px;"><i>What is F-Chat?</i></h2>
                <p>F-Chat is a simple chat app by <b>Frederik Schier</b>, made with the micro web framework <b>Flask</b> for the programming language
                <b>Python</b>. It allows communication with other users through individual chat rooms that the user is
                    able to create himself. He can manage his created rooms at any time by adding a user, removing a user, clearing the room or completely deleting it.
                    F-Chat is <b>Open Source</b> and the Source Code can be found <a href="https://github.com/Freddy382/flask-chat-app">here</a>.
                </p>
            <h2 style="padding: 20px;"><i>How does F-Chat work?</i></h2>
                <h3>Networking</h3>
                <p>In order to establish a connection between the different users and the server, F-Chat uses the python module <b>Flask-SocketIO</b>.
                    It allows many clients to connect to the server which is then going to handle the different clients and group them into
                    rooms. The server-side of the app is written in <b>Python</b> and the client-browser-side in <b>JavaScript</b>.
                    The clients and the server are able to communicate through so-called events which are triggered based on  an action on the client side.
                    When a user for example logs into the chat app, the join event on the client-side is triggered which it emits to the server-side using the Flask-SocketIO module. The server side
                    receives and handles it and then broadcasts it to the other users in the joined room.</p>
                <h3>Data Saving</h3>
                <p>All the data that the app needs are saved in a <b>PostgreSQL</b> database which the server accesses and modifies using the python module <b>Flask-SQLAlchemy</b>.
                    The database contains users, rooms and messages, which are accessed and changed during runtime.<b><u>The passwords of all users are hashed and are therefore not visible for the admin</u></b>.</p>
                <h3>Session Management</h3>
                <p>Data only relevant while the user is logged in is not saved in the Database. Instead, it is saved in the user session which is made with the <b>Flask-Session</b> python module
                    It contains data about the current room the user is in as well as the username of the user which is used for rendering the HTML templates.</p>
                <h3>Hosting</h3>
                <p>F-Chat is running on the cloud and is deployed on the cloud platform <b>Heroku</b>. During development times, it was hosted locally on the developer's machine but was then
                moved to the cloud for production. The cloud application gets the code from the projects GitHub repository and rebuilds the program as soon as changes are made to it.</p>
            <h2 style="padding: 20px;">API</h2>
                <p>F-Chat offers a simple API that can be used by every user. It offers an easy way to analyze the app's data by querying the database.
                    In order to use it, you need to get an <b>API token</b>. A description on how you can get this token can be found below.</p>
                <h3>Endpoints</h3><br>
                <ul style="list-style-type: none">
                    <li>Get token: You need to pass your username as well as your password in json format<i>/api/token</i></li>
                    <li><i></i></li>
                    <li><i></i></li>
                    <li><i></i></li>
                    <li><i></i></li><br>
                <h3>Example</h3>
                    <div class="code" style="text-align: left;">
                        <pre>

<code>import requests
import json

url = "https://f-chat-frederik.herokuapp.com/api"

payload = json.dumps({
  "username": "<b>YOUR USERNAME</b>",
  "password": "<b>YOUR PASSWORD</b>"
})

token_request = requests.get(f"{url}/token", headers=
    {"Content-Type": "application/json"}, data=payload)

access_token = token_request.json()["access_token"]

headers = {
  "Content-Type": "application/json",
  "Authorization": f"Bearer {access_token}"
}

request = requests.get(f"{url}/user/all", headers=headers)

print(request.text, request.status_code)</code>
                        </pre>
                    </div>
                </ul>
        </div>

{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <head>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.1/socket.io.js" integrity="sha512-q/dWJ3kcmjBLU4Qc47E4A9kTB4m3wuTY7vkFJDTZKjTs8jhyGQnaUrxa0Ytd0ssMZhbNua9hE+E7Qv1j+DyZwA==" crossorigin="anonymous"></script>
        <script
          src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
          integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
          crossorigin="anonymous"
        ></script>

        <link rel="stylesheet" href="../static/css/style.css">
        <link rel="stylesheet" href="../static/css/all.min.css">
    </head>

    <title>{% block title%} Home {% endblock %}</title>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script>
        function delete_flash(flash){
            $(flash).parent().remove()
        }
    </script>

    <body>
        <div class="hero">
            <div class="flashed-messages">
                {% with messages = get_flashed_messages(with_categories=true) %} {% if
                messages %} {% for category, message in messages %} {% if category ==
                'error' %}
                <div class="flash-error" role="alert">
                    <p>{{ message }}</p>
                  <button type="button" class="close" onclick=delete_flash(this)>
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                {% else %}
                <div class="flash-success" role="alert">
                    <p>{{ message }}</p>
                  <button type="button" class="close" onclick=delete_flash(this)>
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                {% endif %} {% endfor %} {% endif %} {% endwith %}
            </div>

            <div class="navbar">
                <h1 class="logo">F-CHAT</h1>

                <div class="bars">
                    <i class="fas fa-bars" onclick="showMenu()"></i>
                </div>

                <ul id="nav-links">
                    <div class="close">
                        <i class="fas fa-times" onclick="hideMenu()"></i>
                    </div>

                    <li><a href="/">Home</a></li>

                    {% if user.is_authenticated%}
                          <li><a href="/chat">Chat</a></li>
                          <li><a href="/logout">Logout</a></li>
                          <li><a href="/create-room">Create room</a></li>
                    {% else %}
                        <li><a href="/login">Login</a></li>
                        <li><a href="/sign-up">Sign up</a></li>
                    {% endif %}

                    <li><a href="/about">About</a></li>

                </ul>
            </div>

            <div class="content">
                {% block content %} {% endblock %}
            </div>
        </div>
    </body>

    <script>
        var navbar = document.getElementById('nav-links');
        function showMenu() {
            navbar.style.right = '0';
        }
        function hideMenu() {
            navbar.style.right = '-200px';
        }
    </script>
</html>

app/templates/chat.html
{% extends "base.html" %} {% block title %} Chat {% endblock %}
{% from 'field-macro.html' import displayField %}
{% block content %}

<h1 class="chat-heading">Chat</h1><br>

<head>
    <script type="text/javascript" src="../static/scripts/chat.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.1/socket.io.js" integrity="sha512-q/dWJ3kcmjBLU4Qc47E4A9kTB4m3wuTY7vkFJDTZKjTs8jhyGQnaUrxa0Ytd0ssMZhbNua9hE+E7Qv1j+DyZwA==" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="../static/css/chat.css">
</head>

<div class="container">
        <div id="display-current-room">
            <h2>Room</h2><br>
            <p id="get-room">{{current_room.room_name}}</p>
        </div>

        <div id="display-room-members">
            <h3 align="center">Members</h3><br>
            <ul class="member-list">
            {% for member in current_room.members %}
                {% if member.username == user.username %}
                    <li style="color: red;">{{member.username}}</li>
                {% else %}
                    <li>{{member.username}}</li>
                {% endif %}
                {% if user.username == current_room.owner and member.username != user.username %}
                    <button onclick="removeMember('{{member.username}}', '{{current_room.room_name}}')">X</button>
                {% endif %}
            {% endfor %}
            </ul>
        </div>

        <div id="manage-room">
            {% if current_room.owner == user.username %}
                <h3 align="center">Manage</h3>
                <button  onclick="clearRoom('{{current_room.room_name}}')">Clear</button><br>
                <input id="added-member" placeholder="Member">
                <button onclick="addMember('{{current_room.room_name}}');">Add Member</button>
            {% endif %}
        </div>

        <div id="display-message-section">
            {% for message in current_room.messages %}
                {% if message in user.messages %}
                    {% if message.is_system_message %}
                        <p><i><b>{{ message.content }}</b></i></p>
                    {% else %}
                        {% if message.author == user.username %}
                            <p style="color: red;">{{ message.author }}: {{ message.content }}</p>
                        {% else %}
                            <p>{{ message.author }}: {{ message.content }}</p>
                        {% endif %}
                    {% endif %}
                {% endif %}
            {% endfor %}
        </div>

        <div id="input-area">
            <input type="text" id="user_message" placeholder="Type message..." autocomplete="off">
            <button class="send-button" type="button" id="send_message">Send</button>
        </div>

        <div id="room-section">
            <h2 align="center">Rooms</h2><br>
            <ul class="room-list">
            {% for room in rooms %}
                <li>
                {% if room.owner == user.username %}
                    <button style="color: red;" class="select-room" type="button">{{room.room_name}}</button>
                    <button onclick="deleteRoom('{{room.room_name}}')">X</button>
                {% else %}
                    <button class="select-room" type="button">{{room.room_name}}</button>
                {% endif %}
                </li>

            {% endfor %}
            </ul>
        </div>

        <div id="get-username">{{user.username}}</div>

        <script>

        </script>

</div>

{% endblock %}

app/templates/create_room.html
{% extends "base.html" %} {% block title %} Create Room {% endblock %}
{% from 'field-macro.html' import displayField %}
{% block content %}
  <div class="create-room">
      <script type="text/javascript" src="../static/scripts/chat.js"></script>
      <form method="POST">
        <div class="form-group">
            {{displayField(form.room_name, 'Room name')}}
            {{displayField(form.users, 'Users')}}

            <button type="submit">Create</button>

            {{ form.csrf_token }}
        </div>
      </form>
  </div>

{% endblock %}

app/templates/field-macro.html
{% macro displayField(field, fieldName) %}
    <div class="form-group">
        {{ field(class_='form-control', placeholder=fieldName, **kwargs) }}
    </div>
{% endmacro %}

app/templates/index.html
{% extends "base.html" %} {% block title %} Home {% endblock %}
{% from 'field-macro.html' import displayField %}
{% block content %}
    <div class="index">
        <h1>Welcome to F-CHAT</h1>
        <p>The modern way of chatting on the internet</p>
        <button class="sign-up" type="button" onclick="window.location.href='/sign-up'">Sign Up</button>
        <button class="login" type="button" onclick="window.location.href='/login'">Login</button>
    </div>
{% endblock %}

app/templates/login.html
{% extends "base.html" %} {% block title %} Login {% endblock %}
{% from 'field-macro.html' import displayField %}
{% block content %}
    <div class="login">
         <h1>Login</h1>
            <form action="{{url_for('auth.login')}}", method="POST">
                {{ displayField(form.username, 'Username', autocomplete="off", autofocus=true) }}
                {{ displayField(form.password, 'Password', autocomplete="off", autofocus=true) }}

                {{ form.csrf_token }}

                <button type="submit">Login</button>
            </form>
    </div>


{% endblock %}

app/templates/sign-up.html
{% extends "base.html" %} {% block title %} Sign up {% endblock %}
{% from 'field-macro.html' import displayField %}
{% block content %}
    <div class="sign-up">
        <h1 align="center">Sign up</h1>
            <form action="{{url_for('auth.sign_up')}}", method="POST">
                {{ displayField(form.username, 'Username', autocomplete="off", autofocus=true) }}
                {{ displayField(form.email, 'Email', autocomplete="on", autofocus=true) }}
                {{ displayField(form.password, 'Password', autocomplete="off", autofocus=true) }}
                {{ displayField(form.confirm_password, 'Confirm password', autocomplete="off", autofocus=true) }}

                {{ form.csrf_token }}

                <button type="submit">Register</button>
            </form>
    </div>


{% endblock %}